
name: Code Coverage Report

on:
  push:
    branches:
      - master
jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Run tests with coverage
        run: dotnet test /p:AltCover=true /p:AltCoverAssemblyExcludeFilter="?KmaOoad.Coding.203$"
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
